version "3.8"

services:
  db:
    image: postgres:12.2-alpine
    container_name: "database"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=golang-oauth
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - fullstack
    volumes:
      - database_postgres:/var/lib/postgres/data
  
  web:
    build: .
    container_name: "golang-oauth"
    environment:
      DB_USER: "postgres"
      DB_PASSWORD: "postgres"
      DB_HOST: "db"
      DB_NAME: "golang-oauth"
      DB_PORT: "5432"
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - fullstack


volumes:
  database_postgres:

networks:
  fullstack:
    driver: bridge